language: java
jdk:
- oraclejdk8
script: ./gradlew build jacocoTestReport
before_install:
 - chmod +x gradlew
after_success:
- ./gradlew jacocoRootReport coveralls
cache:
  directories:
  - node_modules