language: java
jdk:
- oraclejdk8
before_install: 
- gradle wrapper --gradle-version 5.1
script: gradle build jacocoTestReport
after_success:
- gradle jacocoRootReport coveralls
cache:
  directories:
  - node_modules